FROM nvcr.io/nvidia/pytorch:23.11-py3

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update


RUN pip install --upgrade pip

WORKDIR /app

COPY ./requirements.txt /app
RUN pip install -r /app/requirements.txt

# Install PyTorch and torchvision
RUN pip3 install torch torchvision torchaudio -f https://download.pytorch.org/whl/cu111/torch_stable.html

# Set the working directory
WORKDIR /app

COPY /notebooks/. /app/notebooks
COPY /scripts/. /app/scripts
COPY /images/. /app/scripts

ENV PYTHONPATH="${PYTHONPATH}:/app"